//************输出***********************
sbit  Signal1    =  P4^6;	//信号强度灯1
sbit  Signal2    =  P4^5;	//信号强度灯2
sbit  Signal3    =  P2^7;	//信号强度灯3
sbit  Signal4    =  P2^6;	//信号强度灯4

sbit  STA4        =  P4^2;	//
sbit  STB4        =  P4^3;	//
sbit  AUX4        =  P3^6;	//

sbit  GSM_SVR    =  P0^5;	//
sbit  GSM_RST    =  P0^6;	//
sbit  DATA_CMD   =  P0^7;	//

sbit  WIFI_RST   =  P0^4;	//
//sbit  WIFI_nLink =  P2^4;	//

sbit  BLU_SCL    =  P3^3;	//
sbit  BLU_SDA    =  P3^4;	//

/////////////////////////////////////////////
sbit  BEEP_pin    = P2^0;
sbit  LED_pin     = P3^4;
sbit  SD2405_SDA  = P3^3;
sbit  SD2405_SCL  = P3^2;
sbit  PLUSE_pin   = P1^7;	   
sbit  RS485S3_pin = P4^4;
sbit  RS485S4_pin = P4^5;

										    



